version: "3.9"
services:
  localstack_test:
    image: localstack/localstack:latest
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - localstack.env
    networks:
      main:
        aliases:
          - localstack_test
    # healtcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  reverse_proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    deploy:
      replicas: 1
    ports:
      - "8080:80"
    networks:
      main:
        aliases:
          - reverse_proxy

  httpd:
    image: httpd:latest
    deploy:
      replicas: 1
    networks:
      main:
        aliases:
          - httpd

networks:
  main: